In [10]:
# ライブラリを追加する
import numpy as np

# 行列A、Bを作成する
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6,7]])

# 行列の積を計算する
np.dot(A, B)
dot = np.dot(A, B)

# 計算結果を表示する
print(dot)

# 行列の要素の最大値を求める
dot_max = np.max(dot)

# 計算結果を表示する
print(dot_max)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
